default:
  image: ruby:3.2

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'

.old_ruby_template: &old_ruby_template
  image: ruby:${RUBY_VERSION}
  stage: test
  script:
    - gem install rubygems-update -v 3.4.22 > /dev/null 2>&1
    - update_rubygems > /dev/null 2>&1
    - bundle config --local path vendor
    - bundle install --quiet --jobs 4 --retry 3
    - bundle exec rake test
  cache:
    key: ${CI_JOB_IMAGE}
    paths:
      - vendor/ruby

.current_ruby_template: &current_ruby_template
  image: ruby:${RUBY_VERSION}
  stage: test
  script:
    - gem update --system > /dev/null 2>&1
    - bundle config --local path vendor
    - bundle install --quiet --jobs 4 --retry 3
    - bundle exec rake test
  cache:
    key: ${CI_JOB_IMAGE}
    paths:
      - vendor/ruby

old-ruby:
  <<: *old_ruby_template
  parallel:
    matrix:
      - RUBY_VERSION: ["2.7", "3.0"]

current-ruby:
  <<: *current_ruby_template
  parallel:
    matrix:
      - RUBY_VERSION: ["3.1", "3.2", "3.3", "3.4"]
