# NOTE: Would make sense to track spec.required_ruby_version in the gemspec,
#       However, it is more valuable to dog-food every config this gem provides by loading config/ruby-1.8.yml
inherit_from:
  - config/ruby-1.8.yml

require:
  - rubocop-rake
  - rubocop-rspec