inherit_gem:
  rubocop-lts: rubocop-lts.yml

# Metrics cops are disabled in Standard by default
Metrics:
  Enabled: true

# Ruby specific customizations
Layout/LineLength:
  Max: 120

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Enabled: true

ThreadSafety/ClassInstanceVariable:
  Enabled: true
  Exclude:
    - bin/bundle
