# NOTE: Would make sense to track spec.required_ruby_version in the gemspec,
#       However, it is more valuable to dog-food every config this gem provides by loading config/ruby-1.8.yml
inherit_from:
  - config/ruby-1.8.yml

require:
  - rubocop-md
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  # RuboCop Gradual can be used in "Require mode", which is a way to replace rubocop with rubocop-gradual:
  - rubocop/gradual/patch

inherit_gem:
  rspec-block_is_expected: rubocop.yml
