# We want Exclude and Include directives from different
#   config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude
    - Include

require:
  - standard-rubocop-lts
  - standard
  - standard-performance
  - standard-custom
  - rubocop-performance

# Load basic rules for this version of Ruby from standard.
# Rules are overridden in a LIFO stack.
# If rubocop-performance is listed first, and standard-performance after it,
#   then rubocop-performance's rules will take precedence.
# This is the opposite of what you might expect.
# Below: standard's rules override rubocop-performance's (mostly disabling rules)
inherit_gem:
  standard: config/ruby-2.5.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  rubocop-performance: config/default.yml

inherit_from:
  - ./base.yml
  - ./internal/ruby-2.5.yml
