# See:
#   https://github.com/rubocop/rubocop-performance/issues/240
#   https://github.com/rubocop/rubocop-performance/pull/241
Performance/Casecmp:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1375527811
Performance/BlockGivenWithExplicitBlock:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/BigDecimalWithNumericArgument:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/IoReadlines:
  Enabled: false
