# Alphabetizing lists enforces minimal churn in git history post-correction
Bundler/OrderedGems:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: true
  EnforcedStyle: required

# See: https://github.com/rubygems/rubygems/discussions/5065#discussioncomment-7031586
Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: gemspec

# Alphabetizing lists enforces minimal churn in git history
Gemspec/OrderedDependencies:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: true

Gemspec/RubyVersionGlobalsUsage:
  Enabled: true

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/BigDecimalWithNumericArgument:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1375527811
Performance/BlockGivenWithExplicitBlock:
  Enabled: false

# See:
#   https://github.com/rubocop/rubocop-performance/issues/240
#   https://github.com/rubocop/rubocop-performance/pull/241
Performance/Casecmp:
  Enabled: false

# See: https://github.com/rubocop/rubocop-performance/issues/329#issuecomment-1451511402
Performance/IoReadlines:
  Enabled: false

# This cop is 66% incorrect, and hasn't been fixed in 2+ years.
# See: https://github.com/rubocop/rubocop-rake/issues/42
Rake/MethodDefinitionInTask:
  Enabled: false
